#!/usr/bin/env python3
"""Render a self-contained AGENTS.md from shared and repository-local policy."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_lock(path: Path, shared: Path) -> tuple[dict[str, object], str]:
    try:
        lock = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read policy lock {path}: {exc}") from exc

    required = {
        "source_repository",
        "source_revision",
        "source_path",
        "renderer_path",
        "shared_sha256",
        "renderer_sha256",
    }
    if not isinstance(lock, dict) or not required.issubset(lock):
        raise ValueError(f"{path} must define: {', '.join(sorted(required))}")

    revision = lock["source_revision"]
    if not isinstance(revision, str) or len(revision) != 40 or any(
        char not in "0123456789abcdef" for char in revision.lower()
    ):
        raise ValueError(f"{path}: source_revision must be a 40-character Git SHA")

    shared_digest = lock["shared_sha256"]
    if not isinstance(shared_digest, str) or sha256(shared) != shared_digest:
        raise ValueError(f"{shared} does not match shared_sha256 in {path}")

    renderer_digest = lock["renderer_sha256"]
    renderer = Path(__file__).resolve()
    if not isinstance(renderer_digest, str) or sha256(renderer) != renderer_digest:
        raise ValueError(f"{renderer} does not match renderer_sha256 in {path}")

    label = f"{lock['source_repository']}@{revision}:{lock['source_path']}"
    return lock, label


def sync_upstream(lock_path: Path, shared_path: Path, revision: str) -> None:
    if len(revision) != 40 or any(char not in "0123456789abcdef" for char in revision.lower()):
        raise ValueError("--sync-ref must be a full 40-character Git commit SHA")
    try:
        lock = json.loads(lock_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read policy lock {lock_path}: {exc}") from exc
    if not isinstance(lock, dict):
        raise ValueError(f"{lock_path} must contain a JSON object")

    repository = lock.get("source_repository")
    source_path = lock.get("source_path")
    renderer_path = lock.get("renderer_path")
    if not all(isinstance(value, str) and value for value in (repository, source_path, renderer_path)):
        raise ValueError(f"{lock_path} must define source_repository, source_path, and renderer_path")
    if len(repository.split("/")) != 2 or any(part in (".", "..") for part in repository.split("/")):
        raise ValueError(f"{lock_path}: invalid source_repository")
    if any(part in (".", "..") for part in Path(source_path).parts + Path(renderer_path).parts):
        raise ValueError(f"{lock_path}: source paths must not traverse parent directories")

    def fetch(path: str) -> bytes:
        url = f"https://raw.githubusercontent.com/{repository}/{revision}/{path}"
        try:
            with urllib.request.urlopen(url, timeout=20) as response:
                return response.read()
        except (OSError, urllib.error.URLError) as exc:
            raise ValueError(f"could not fetch pinned policy source {url}: {exc}") from exc

    # Fetch and decode everything before replacing any local file.
    shared_bytes = fetch(source_path)
    renderer_bytes = fetch(renderer_path)
    try:
        shared_bytes.decode("utf-8")
        renderer_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError("upstream agent policy files must be UTF-8 text") from exc

    shared_path.write_bytes(shared_bytes)
    renderer_path_local = Path(__file__).resolve()
    renderer_path_local.write_bytes(renderer_bytes)
    lock["source_revision"] = revision.lower()
    lock["shared_sha256"] = hashlib.sha256(shared_bytes).hexdigest()
    lock["renderer_sha256"] = hashlib.sha256(renderer_bytes).hexdigest()
    lock_path.write_text(json.dumps(lock, indent=2) + "\n", encoding="utf-8")


def render(shared: Path, local: Path, label: str) -> str:
    shared_text = shared.read_text(encoding="utf-8").strip()
    local_text = local.read_text(encoding="utf-8").strip()
    return (
        "<!-- Generated by scripts/render-agent-instructions.py; edit the source files. -->\n"
        f"<!-- Shared policy source: {label} -->\n\n"
        f"{shared_text}\n\n{local_text}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--shared", type=Path, required=True)
    parser.add_argument("--local", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--source-label", default="shared policy")
    parser.add_argument("--lock", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--sync-ref", help="fetch shared policy and renderer from this full upstream commit SHA")
    args = parser.parse_args()

    try:
        if args.sync_ref:
            if not args.lock or args.check:
                raise ValueError("--sync-ref requires --lock and cannot be combined with --check")
            sync_upstream(args.lock, args.shared, args.sync_ref)
        label = args.source_label
        if args.lock:
            _, label = load_lock(args.lock, args.shared)
        expected = render(args.shared, args.local, label)
        if args.check:
            try:
                actual = args.output.read_text(encoding="utf-8")
            except OSError as exc:
                raise ValueError(f"cannot read generated file {args.output}: {exc}") from exc
            if actual != expected:
                print(f"{args.output} is out of date; rerun the renderer", file=sys.stderr)
                return 1
            print(f"{args.output} matches its shared and repository-local sources")
            return 0
        args.output.write_text(expected, encoding="utf-8")
        print(f"Rendered {args.output}")
        return 0
    except (OSError, ValueError) as exc:
        print(exc, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
